name: practicalchat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  dio: ^5.3.4
  socket_io_client: ^2.0.3+1
  get_storage: ^2.1.1
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.2.0
  zego_uikit_prebuilt_call: ^3.17.9
  flutter_ringtone_player: ^3.2.0
  intl: ^0.18.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

